import { Inter } from "next/font/google";
import "./globals.css";
import Navbare from "@/components/side/Navbare";
import Footer from "@/components/side/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Najia Ait Rabhi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
